# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 02:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('EZtradrApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='adjClose',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='high',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='low',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='open',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='volume',
            field=models.IntegerField(default=0.0),
        ),
    ]
