# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZtradrApp', '0003_auto_20170130_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='adjClose',
            field=models.CharField(max_length=50),
        ),
    ]
