# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EZtradrApp', '0004_auto_20170130_0226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='close',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='high',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='stock',
            name='low',
            field=models.CharField(max_length=50),
        ),
    ]
